-- 1) Set role
USE ROLE TRAINING_ROLE;

-- 2) Compute
CREATE OR REPLACE WAREHOUSE ADO_GROUP3_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- 3) Storage
CREATE DATABASE IF NOT EXISTS ADO_GROUP3_DB;

-- 4) Layering 
CREATE SCHEMA IF NOT EXISTS ADO_GROUP3_DB.RAW;
CREATE SCHEMA IF NOT EXISTS ADO_GROUP3_DB.ANALYTICS;

-- 5) Set context
USE WAREHOUSE ADO_GROUP3_WH;
USE DATABASE ADO_GROUP3_DB;
USE SCHEMA ADO_GROUP3_DB.RAW;

-- 6) File format
CREATE OR REPLACE FILE FORMAT FF_CSV_STD
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL', 'null');

-- 7) Stage
-- To temporarily store CSV files     --
-- Links the stage to the file format --
CREATE OR REPLACE STAGE STG_CSV
  FILE_FORMAT = FF_CSV_STD;

-- 8) Suspend warehouse (cost control)
ALTER WAREHOUSE ADO_GROUP3_WH SUSPEND;



-- master data
SELECT *
FROM members
LIMIT 10;

-- IDS Mapping 
SELECT *
FROM ADMISSION_SOURCE
LIMIT 10;

SELECT *
FROM ADMISSION_TYPE
LIMIT 10;

SELECT *
FROM DISCHARGE_DISPOSITION
LIMIT 10;

-- Suspend 
ALTER WAREHOUSE ADO_GROUP3_WH SUSPEND;






