USE ROLE TRAINING_ROLE;

CREATE OR REPLACE WAREHOUSE ADO_GROUP3_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE ADO_GROUP3_DB;
CREATE OR REPLACE SCHEMA ADO_GROUP3_DB.RAW;
CREATE OR REPLACE SCHEMA ADO_GROUP3_DB.ANALYTICS;

USE WAREHOUSE ADO_GROUP3_WH;
USE DATABASE ADO_GROUP3_DB;
USE SCHEMA ADO_GROUP3_DB.RAW;

CREATE OR REPLACE FILE FORMAT FF_CSV_STD
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL', 'null');

SELECT
  CURRENT_ROLE(),
  CURRENT_WAREHOUSE(),
  CURRENT_DATABASE(),
  CURRENT_SCHEMA();

CREATE OR REPLACE STAGE STG_DIABETES
FILE_FORMAT = FF_CSV_STD;

LIST @STG_DIABETES;

USE DATABASE ADO_GROUP3_DB;
USE SCHEMA RAW;

DROP TABLE IF EXISTS RAW.DIABETIC_DATA;

CREATE OR REPLACE TABLE RAW.DIABETIC_DATA (
    encounter_id NUMBER,
    patient_nbr NUMBER,
    race VARCHAR,
    gender VARCHAR,
    age VARCHAR,
    weight VARCHAR,
    admission_type_id NUMBER,
    discharge_disposition_id NUMBER,
    admission_source_id NUMBER,
    time_in_hospital NUMBER,
    payer_code VARCHAR,
    medical_specialty VARCHAR,
    num_lab_procedures NUMBER,
    num_procedures NUMBER,
    num_medications NUMBER,
    number_outpatient NUMBER,
    number_emergency NUMBER,
    number_inpatient NUMBER,
    diag_1 VARCHAR,
    diag_2 VARCHAR,
    diag_3 VARCHAR,
    number_diagnoses NUMBER,
    max_glu_serum VARCHAR,
    A1Cresult VARCHAR,
    metformin VARCHAR,
    repaglinide VARCHAR,
    nateglinide VARCHAR,
    chlorpropamide VARCHAR,
    glimepiride VARCHAR,
    acetohexamide VARCHAR,
    glipizide VARCHAR,
    glyburide VARCHAR,
    tolbutamide VARCHAR,
    pioglitazone VARCHAR,
    rosiglitazone VARCHAR,
    acarbose VARCHAR,
    miglitol VARCHAR,
    troglitazone VARCHAR,
    tolazamide VARCHAR,
    examide VARCHAR,
    citoglipton VARCHAR,
    insulin VARCHAR,
    glyburide_metformin VARCHAR,
    glipizide_metformin VARCHAR,
    glimepiride_pioglitazone VARCHAR,
    metformin_rosiglitazone VARCHAR,
    metformin_pioglitazone VARCHAR,
    change VARCHAR,
    diabetesMed VARCHAR,
    readmitted VARCHAR
);

COPY INTO RAW.DIABETIC_DATA
FROM @STG_DIABETES
FILE_FORMAT = FF_CSV_STD
ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*) FROM RAW.DIABETIC_DATA;

DESC TABLE RAW.DIABETIC_DATA;

SELECT COUNT(*) AS table_cols
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'RAW'
  AND TABLE_NAME = 'DIABETIC_DATA';

SELECT COUNT(*) AS row_count
FROM RAW.DIABETIC_DATA;

CREATE OR REPLACE SCHEMA ADO_GROUP3_DB.STG;
USE DATABASE ADO_GROUP3_DB;
USE SCHEMA STG;

CREATE OR REPLACE TABLE STG.DIABETIC_DATA_CLEAN AS
SELECT
    ENCOUNTER_ID,
    PATIENT_NBR,

    COALESCE(NULLIF(TRIM(RACE), ''), 'Unknown') AS RACE,

    CASE
        WHEN LOWER(TRIM(GENDER)) = 'male' THEN 'M'
        WHEN LOWER(TRIM(GENDER)) = 'female' THEN 'F'
        ELSE 'Unknown'
    END AS GENDER,

    TRIM(AGE) AS AGE,

    ADMISSION_TYPE_ID,
    DISCHARGE_DISPOSITION_ID,
    ADMISSION_SOURCE_ID,
    TIME_IN_HOSPITAL,
    NUM_LAB_PROCEDURES,
    NUM_PROCEDURES,
    NUM_MEDICATIONS,
    NUMBER_OUTPATIENT,
    NUMBER_EMERGENCY,
    NUMBER_INPATIENT,

    TRIM(DIAG_1) AS DIAG_1,
    TRIM(DIAG_2) AS DIAG_2,
    TRIM(DIAG_3) AS DIAG_3,

    NUMBER_DIAGNOSES,

    COALESCE(NULLIF(TRIM(MAX_GLU_SERUM), ''), 'None') AS MAX_GLU_SERUM,
    COALESCE(NULLIF(TRIM(A1CRESULT), ''), 'None')     AS A1CRESULT,

    METFORMIN,
    REPAGLINIDE,
    NATEGLINIDE,
    CHLORPROPAMIDE,
    GLIMEPIRIDE,
    ACETOHEXAMIDE,
    GLIPIZIDE,
    GLYBURIDE,
    TOLBUTAMIDE,
    PIOGLITAZONE,
    ROSIGLITAZONE,
    ACARBOSE,
    MIGLITOL,
    TROGLITAZONE,
    TOLAZAMIDE,
    EXAMIDE,
    INSULIN,
    GLYBURIDE_METFORMIN,
    GLIPIZIDE_METFORMIN,
    GLIMEPIRIDE_PIOGLITAZONE,
    METFORMIN_PIOGLITAZONE,
    CHANGE,
    DIABETESMED,
    READMITTED,

    CASE WHEN READMITTED = '<30' THEN 1 ELSE 0 END AS READMIT_30D
FROM RAW.DIABETIC_DATA
WHERE DIAG_1 IS NOT NULL
  AND DIAG_2 IS NOT NULL
  AND DIAG_3 IS NOT NULL;

SHOW TABLES IN SCHEMA ADO_GROUP3_DB.STG;

SELECT COUNT(*) FROM STG.DIABETIC_DATA_CLEAN;

DESC TABLE STG.DIABETIC_DATA_CLEAN;

SELECT RACE, COUNT(*)
FROM STG.DIABETIC_DATA_CLEAN
GROUP BY RACE
ORDER BY COUNT(*) DESC;

USE SCHEMA STG;

CREATE OR REPLACE TABLE STG.DIABETIC_DATA_CLEAN AS
SELECT
    ENCOUNTER_ID,
    PATIENT_NBR,

    /* race: treat '?' as NULL, then fill Unknown */
    COALESCE(NULLIF(NULLIF(TRIM(RACE), '?'), ''), 'Unknown') AS RACE,

    /* gender: standardise */
    CASE
        WHEN LOWER(TRIM(GENDER)) = 'male' THEN 'M'
        WHEN LOWER(TRIM(GENDER)) = 'female' THEN 'F'
        ELSE 'Unknown'
    END AS GENDER,

    TRIM(AGE) AS AGE,

    ADMISSION_TYPE_ID,
    DISCHARGE_DISPOSITION_ID,
    ADMISSION_SOURCE_ID,
    TIME_IN_HOSPITAL,
    NUM_LAB_PROCEDURES,
    NUM_PROCEDURES,
    NUM_MEDICATIONS,
    NUMBER_OUTPATIENT,
    NUMBER_EMERGENCY,
    NUMBER_INPATIENT,

    TRIM(DIAG_1) AS DIAG_1,
    TRIM(DIAG_2) AS DIAG_2,
    TRIM(DIAG_3) AS DIAG_3,

    NUMBER_DIAGNOSES,

    /* fill missing lab results */
    COALESCE(NULLIF(NULLIF(TRIM(MAX_GLU_SERUM), '?'), ''), 'None') AS MAX_GLU_SERUM,
    COALESCE(NULLIF(NULLIF(TRIM(A1CRESULT), '?'), ''), 'None')     AS A1CRESULT,

    /* meds */
    TRIM(METFORMIN) AS METFORMIN,
    TRIM(REPAGLINIDE) AS REPAGLINIDE,
    TRIM(NATEGLINIDE) AS NATEGLINIDE,
    TRIM(CHLORPROPAMIDE) AS CHLORPROPAMIDE,
    TRIM(GLIMEPIRIDE) AS GLIMEPIRIDE,
    TRIM(ACETOHEXAMIDE) AS ACETOHEXAMIDE,
    TRIM(GLIPIZIDE) AS GLIPIZIDE,
    TRIM(GLYBURIDE) AS GLYBURIDE,
    TRIM(TOLBUTAMIDE) AS TOLBUTAMIDE,
    TRIM(PIOGLITAZONE) AS PIOGLITAZONE,
    TRIM(ROSIGLITAZONE) AS ROSIGLITAZONE,
    TRIM(ACARBOSE) AS ACARBOSE,
    TRIM(MIGLITOL) AS MIGLITOL,
    TRIM(TROGLITAZONE) AS TROGLITAZONE,
    TRIM(TOLAZAMIDE) AS TOLAZAMIDE,
    TRIM(EXAMIDE) AS EXAMIDE,
    TRIM(INSULIN) AS INSULIN,
    TRIM(GLYBURIDE_METFORMIN) AS GLYBURIDE_METFORMIN,
    TRIM(GLIPIZIDE_METFORMIN) AS GLIPIZIDE_METFORMIN,
    TRIM(GLIMEPIRIDE_PIOGLITAZONE) AS GLIMEPIRIDE_PIOGLITAZONE,
    TRIM(METFORMIN_ROSIGLITAZONE) AS METFORMIN_ROSIGLITAZONE,
    TRIM(METFORMIN_PIOGLITAZONE) AS METFORMIN_PIOGLITAZONE,

    TRIM(CHANGE) AS CHANGE,
    TRIM(DIABETESMED) AS DIABETESMED,
    TRIM(READMITTED) AS READMITTED,

    /* target flag */
    CASE WHEN TRIM(READMITTED) = '<30' THEN 1 ELSE 0 END AS READMIT_30D

FROM RAW.DIABETIC_DATA
WHERE DIAG_1 IS NOT NULL
  AND DIAG_2 IS NOT NULL
  AND DIAG_3 IS NOT NULL;

  -- row count after dropping DIAG nulls
SELECT COUNT(*) AS stg_rows FROM STG.DIABETIC_DATA_CLEAN;

-- confirm no '?' in race anymore
SELECT RACE, COUNT(*)
FROM STG.DIABETIC_DATA_CLEAN
GROUP BY RACE
ORDER BY COUNT(*) DESC;

-- confirm lab imputations
SELECT MAX_GLU_SERUM, COUNT(*) FROM STG.DIABETIC_DATA_CLEAN GROUP BY MAX_GLU_SERUM ORDER BY COUNT(*) DESC;
SELECT A1CRESULT, COUNT(*) FROM STG.DIABETIC_DATA_CLEAN GROUP BY A1CRESULT ORDER BY COUNT(*) DESC;

-- confirm gender standardisation
SELECT GENDER, COUNT(*) FROM STG.DIABETIC_DATA_CLEAN GROUP BY GENDER;

CREATE OR REPLACE TABLE STG.DIABETIC_DATA_OUTLIERS AS
WITH iqr AS (
  SELECT
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY TIME_IN_HOSPITAL)     AS q1_time,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY TIME_IN_HOSPITAL)     AS q3_time,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NUM_LAB_PROCEDURES)   AS q1_lab,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NUM_LAB_PROCEDURES)   AS q3_lab,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NUM_PROCEDURES)       AS q1_proc,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NUM_PROCEDURES)       AS q3_proc,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NUM_MEDICATIONS)      AS q1_meds,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NUM_MEDICATIONS)      AS q3_meds,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NUMBER_OUTPATIENT)    AS q1_outp,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NUMBER_OUTPATIENT)    AS q3_outp,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NUMBER_EMERGENCY)     AS q1_emer,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NUMBER_EMERGENCY)     AS q3_emer,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NUMBER_INPATIENT)     AS q1_inp,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NUMBER_INPATIENT)     AS q3_inp,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NUMBER_DIAGNOSES)     AS q1_diag,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NUMBER_DIAGNOSES)     AS q3_diag
  FROM STG.DIABETIC_DATA_CLEAN
)
SELECT
  d.*,

  (d.TIME_IN_HOSPITAL < (q1_time - 1.5*(q3_time - q1_time)) OR d.TIME_IN_HOSPITAL > (q3_time + 1.5*(q3_time - q1_time))) AS outlier_time_in_hospital,
  (d.NUM_LAB_PROCEDURES < (q1_lab - 1.5*(q3_lab - q1_lab)) OR d.NUM_LAB_PROCEDURES > (q3_lab + 1.5*(q3_lab - q1_lab)))   AS outlier_num_lab_procedures,
  (d.NUM_PROCEDURES < (q1_proc - 1.5*(q3_proc - q1_proc)) OR d.NUM_PROCEDURES > (q3_proc + 1.5*(q3_proc - q1_proc)))     AS outlier_num_procedures,
  (d.NUM_MEDICATIONS < (q1_meds - 1.5*(q3_meds - q1_meds)) OR d.NUM_MEDICATIONS > (q3_meds + 1.5*(q3_meds - q1_meds)))    AS outlier_num_medications,
  (d.NUMBER_OUTPATIENT < (q1_outp - 1.5*(q3_outp - q1_outp)) OR d.NUMBER_OUTPATIENT > (q3_outp + 1.5*(q3_outp - q1_outp))) AS outlier_number_outpatient,
  (d.NUMBER_EMERGENCY < (q1_emer - 1.5*(q3_emer - q1_emer)) OR d.NUMBER_EMERGENCY > (q3_emer + 1.5*(q3_emer - q1_emer))) AS outlier_number_emergency,
  (d.NUMBER_INPATIENT < (q1_inp - 1.5*(q3_inp - q1_inp)) OR d.NUMBER_INPATIENT > (q3_inp + 1.5*(q3_inp - q1_inp)))       AS outlier_number_inpatient,
  (d.NUMBER_DIAGNOSES < (q1_diag - 1.5*(q3_diag - q1_diag)) OR d.NUMBER_DIAGNOSES > (q3_diag + 1.5*(q3_diag - q1_diag))) AS outlier_number_diagnoses,

  (
    (d.TIME_IN_HOSPITAL < (q1_time - 1.5*(q3_time - q1_time)) OR d.TIME_IN_HOSPITAL > (q3_time + 1.5*(q3_time - q1_time)))
    OR (d.NUM_LAB_PROCEDURES < (q1_lab - 1.5*(q3_lab - q1_lab)) OR d.NUM_LAB_PROCEDURES > (q3_lab + 1.5*(q3_lab - q1_lab)))
    OR (d.NUM_PROCEDURES < (q1_proc - 1.5*(q3_proc - q1_proc)) OR d.NUM_PROCEDURES > (q3_proc + 1.5*(q3_proc - q1_proc)))
    OR (d.NUM_MEDICATIONS < (q1_meds - 1.5*(q3_meds - q1_meds)) OR d.NUM_MEDICATIONS > (q3_meds + 1.5*(q3_meds - q1_meds)))
    OR (d.NUMBER_OUTPATIENT < (q1_outp - 1.5*(q3_outp - q1_outp)) OR d.NUMBER_OUTPATIENT > (q3_outp + 1.5*(q3_outp - q1_outp)))
    OR (d.NUMBER_EMERGENCY < (q1_emer - 1.5*(q3_emer - q1_emer)) OR d.NUMBER_EMERGENCY > (q3_emer + 1.5*(q3_emer - q1_emer)))
    OR (d.NUMBER_INPATIENT < (q1_inp - 1.5*(q3_inp - q1_inp)) OR d.NUMBER_INPATIENT > (q3_inp + 1.5*(q3_inp - q1_inp)))
    OR (d.NUMBER_DIAGNOSES < (q1_diag - 1.5*(q3_diag - q1_diag)) OR d.NUMBER_DIAGNOSES > (q3_diag + 1.5*(q3_diag - q1_diag)))
  ) AS flagged_outlier

FROM STG.DIABETIC_DATA_CLEAN d
CROSS JOIN iqr;

SELECT
  SUM(IFF(flagged_outlier,1,0)) AS rows_flagged,
  COUNT(*) AS total_rows
FROM STG.DIABETIC_DATA_OUTLIERS;

USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE ANALYTICS.DIABETIC_DATA_FINAL AS
SELECT *
FROM STG.DIABETIC_DATA_OUTLIERS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ENCOUNTER_ID ORDER BY ENCOUNTER_ID) = 1;

SELECT COUNT(*) AS final_rows FROM ANALYTICS.DIABETIC_DATA_FINAL;

SELECT ENCOUNTER_ID, COUNT(*)
FROM ANALYTICS.DIABETIC_DATA_FINAL
GROUP BY ENCOUNTER_ID
HAVING COUNT(*) > 1;



